import mongoose from 'mongoose'

const IndicatorSchema = new mongoose.Schema(
  {
    symbol: {
      type: String,
      required: true,
    },
    interval: {
      type: String,
      required: true,
    },
    RSI: Number,
    RSI1: Number,
    StochK: Number,
    StochD: Number,
    StochK1: Number,
    StochD1: Number,
    CCI20: Number,
    CCI201: Number,
    ADX: Number,
    ADXandDI: Number,
    ADXnotDI: Number,
    ADXandDI1: Number,
    ADXnotDI1: Number,
    AO: Number,
    AO1: Number,
    Mom: Number,
    Mom1: Number,
    MACDmacd: Number,
    MACDsignal: Number,
    RecStochRSI: Number,
    StochRSIK: Number,
    RecWR: Number,
    WR: Number,
    RecBBPower: Number,
    BBPower: Number,
    RecUO: Number,
    UO: Number,
    EMA5: Number,
    SMA5: Number,
    EMA10: Number,
    SMA10: Number,
    EMA20: Number,
    SMA20: Number,
    EMA30: Number,
    SMA30: Number,
    EMA50: Number,
    SMA50: Number,
    EMA100: Number,
    SMA100: Number,
    EMA200: Number,
    SMA200: Number,
    RecIchimoku: Number,
    IchimokuBLine: Number,
    RecVWMA: Number,
    VWMA: Number,
    RecHullMA9: Number,
    HullMA9: Number,
    PivotMClassicS3: Number,
    PivotMClassicS2: Number,
    PivotMClassicS1: Number,
    PivotMClassicMiddle: Number,
    PivotMClassicR1: Number,
    PivotMClassicR2: Number,
    PivotMClassicR3: Number,
    PivotMFibonacciS3: Number,
    PivotMFibonacciS2: Number,
    PivotMFibonacciS1: Number,
    PivotMFibonacciMiddle: Number,
    PivotMFibonacciR1: Number,
    PivotMFibonacciR2: Number,
    PivotMFibonacciR3: Number,
    PivotMCamarillaS3: Number,
    PivotMCamarillaS2: Number,
    PivotMCamarillaS1: Number,
    PivotMCamarillaMiddle: Number,
    PivotMCamarillaR1: Number,
    PivotMCamarillaR2: Number,
    PivotMCamarillaR3: Number,
    PivotMWoodieS3: Number,
    PivotMWoodieS2: Number,
    PivotMWoodieS1: Number,
    PivotMWoodieMiddle: Number,
    PivotMWoodieR1: Number,
    PivotMWoodieR2: Number,
    PivotMWoodieR3: Number,
    PivotMDemarkS1: Number,
    PivotMDemarkMiddle: Number,
    PivotMDemarkR1: Number,
    PSAR: Number,
    BBlower: Number,
    BBupper: Number,
    AO2: Number,
  },
  {
    timestamps: true,
  }
)

export default mongoose.model('Indicator', IndicatorSchema)
